name: Build and Push Docker image to Local

on:
  workflow_dispatch:

env:
  IMAGE_NAME: localhost:5000/maven_check_versions

jobs:
  build-push-docker-image-local:
    runs-on: ubuntu-latest

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Build and push to local registry
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}

      - name: Build and push to local registry (pypy)
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ./pypy.Dockerfile
          tags: ${{ env.IMAGE_NAME }}:pypy

      - name: Inspect
        run: docker buildx imagetools inspect ${{ env.IMAGE_NAME }}

      - name: Inspect (pypy)
        run: docker buildx imagetools inspect ${{ env.IMAGE_NAME }}:pypy
