name: Build and Push Docker image

on:
  workflow_dispatch:
  release:
    types: published

jobs:
  build-push-docker-image:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: alexundros
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: alexundros
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Read VERSION file
        id: version
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/alexundros/maven-check-versions:latest
            ghcr.io/alexundros/maven-check-versions:${{ steps.version.outputs.version }}
            alexundros/maven-check-versions:latest
            alexundros/maven-check-versions:${{ steps.version.outputs.version }}

      - name: Build and push Docker image (pypy)
        uses: docker/build-push-action@v6
        with:
          file: ./pypy.Dockerfile
          push: true
          tags: |
            ghcr.io/alexundros/maven-check-versions:pypy
            ghcr.io/alexundros/maven-check-versions:${{ steps.version.outputs.version }}-pypy
            alexundros/maven-check-versions:pypy
            alexundros/maven-check-versions:${{ steps.version.outputs.version }}-pypy

      # Only if 2FA is disabled and the token has full access
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: alexundros
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: alexundros/maven-check-versions
          readme-filepath: ./DockerHub.md
