name: Python package Create Release

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    tags:
      - "v*"

jobs:
  start:
    runs-on: ubuntu-latest

    permissions:
      contents: write # IMPORTANT for making Releases

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-cov pytest-mock build
        python -m pip install -r requirements.txt

    - name: Test with pytest
      run: pytest

    - name: Read VERSION file
      id: getversion
      run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

    - name: Build project
      run: python -m build

    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release create v${{ github.ref_name }} --notes "" --draft

    - name: Upload Release Asset
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release upload v${{ github.ref_name }} dist/**
