name: Python package Tests SonarQube Scan

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches: [ "main" ]

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest pytest-cov pytest-mock coveralls
        python -m pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: pytest --cov=src --cov-report=xml:coverage.xml --cov-config=tests/.coveragerc

    - name: Upload coverage data to coveralls.io
      if: ${{ github.event_name != 'pull_request' }}
      run: coveralls --rcfile=tests/.coveragerc
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

    - name: Read VERSION file
      id: getversion
      run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v4
      with:
        args: >
          -Dsonar.projectVersion=${{ steps.getversion.outputs.version }}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
