name: Python package Publish to PyPI

on:
  workflow_dispatch:
  release:
    types: published

jobs:
  python-package-publish-pypi:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build twine --user

    - name: Build a binary wheel and a source tarball
      run: python3 -m build

    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-dist
        path: dist/

    - name: Publish to PyPI
      run: twine upload dist/* -u __token__ -p "${{ secrets.PYPI_TOKEN }}"
